### PR TITLE
new: Version 12.1

### PR DESCRIPTION
**Pull request by milesj**
All the new things.

### CODE REVIEW

**Comment by milesj** [comment]
@dbrgn This *should* resolve both your issues. If you have a minute, can you verify against this branch?

**Comment by dbrgn** [comment]
@milesj great! will do, if not today then on monday.

**Comment by milesj** [comment]
@dbrgn Sweet no rush. Need to figure out why the build is failing...

**Comment by dbrgn** [comment]
Sorry, didn't manage to test it yesterday.

Thanks! I noticed that the list at http://xahlee.info/comp/text_vs_emoji.html lists WHITE MEDIUM STAR and MAHJONG TILE RED DRAGON as "text-default" while your data lists them as "type=1". Might be an error on the side of "xahlee.info", but for example the mahjong tile was added to Unicode in 2008 and to Emoji 1.0 in 2015, so I'm not sure if it should be text-default or not.

**Comment by milesj** [comment]
@dbrgn I noticed that list is missing quite a few of them, so I would say it's outdated.

I compared most of them to the official unicode list, which matched 100%. Also compared to emojipedia, which states its an emoji: https://emojipedia.org/emoji/%F0%9F%80%84/

**Comment by dbrgn** [comment]
Ah, great, then that list is probably outdated indeed :slightly_smiling_face: 

Thanks for your work, dealing with emoji is horrible :smile: I don't know how many days of my life I've lost to them...

**Pull request merged**
