### PR TITLE
release: Support emoji v15!

### PR DESCRIPTION
**Pull request by milesj**

### CODE REVIEW

**Comment by lessless** [comment]
🥳

**Comment by b-g** [comment]
Dear @milesj, hope this ping finds you well! We would like to tackle over OpenMoji v15 over the summer ... hence any chance to get emojibase-data to Emoji 15 in the next weeks? We are kind of blocked without have a solid emojibase-data. Sorry to bother! :)

**Comment by milesj** [comment]
@b-g I kind of forgot about this PR 😅 

From what I remember, it's mostly done except for translations, which I hate doing since it's time consuming lol.

**Comment by lessless** [comment]
@milesj pretty please for flying donkey 🫏🪽

**Comment by milesj** [comment]
@b-g @lessless Released!

I believe this PR was already finished, I couldn't find anything missing, so let me know if there are issues.

**Comment by lessless** [comment]
Fantastic, thank you 🥳 !

**Comment by b-g** [comment]
Mega! Many thanks! ❤️

**Pull request merged**
