### PR TITLE
new: Add vi (Vietnamese) language

### PR DESCRIPTION
**Pull request by ZoloPro**

### CODE REVIEW

**Comment by ZoloPro** [comment]
@milesj Please help me review this pull request. If anything needs to be changed, just let me know.

**Comment by milesj** [comment]
@ZoloPro This will need to wait until this PR lands: https://github.com/milesj/emojibase/pull/180

**Comment by milesj** [comment]
That PR landed if you want to rebase and translate the new messages.

**Comment by ZoloPro** [comment]
@milesj I have updated the pull request. Could you please review it?

**Comment by milesj** [comment]
@ZoloPro Just need to add a changeset with `yarn bump`.

**Comment by ZoloPro** [comment]
> @ZoloPro Just need to add a changeset with `yarn bump`.
> 
> It also looks like tests keep hanging. You probably need to update this: https://github.com/milesj/emojibase/blob/master/packages/regex/shortcode-native.js

I have updated

**Comment by milesj** [comment]
Looks good. No idea why that check is failing, probably because its a fork?

Will merge anyways.

**Pull request merged**
