### PR TITLE
new: browser app - initial

### LINKED ISSUE #54: Documentation: User-friendly browser
The documentation links to https://github.com/milesj/emojibase/blob/master/packages/generator/src/resources/shortcodes.ts. I personally think a more user-friendly page with a simple in-page filter, similar to [here](https://unicodey.com/emoji-data/table.htm) might be nice. 

Would you be open to a PR that includes this, or would this kind of thing be best in a separate repo? 

Thanks!

### PR DESCRIPTION
**Pull request by gavinr**
Initial version of a simple emojibase browser app. 

To deploy this using Netlify, use these settings:
image

Example here: https://emojibase-browser.netlify.app/

Resolves #54

Next step: better internationalization (guess locale based on browser settings, using `svelte-i18n`)

### CODE REVIEW

**Comment by gavinr** [comment]
@milesj wanted to check in here - what can I do to get this landed? Thanks!

**Comment by milesj** [comment]
@gavinr Have been busy on a few other projects so haven't had time to look at this. Hoping to by end of July.

**Comment by gavinr** [comment]
sounds great - no problem, just wanted to check in. thanks!

**Comment by milesj** [comment]
@gavinr Ok, been thinking about this. I recently started the process of migrating all my projects docs to docusaurus, which I started with here: https://aesthetic-suite.github.io/website/ I'll most likely be doing the same with emojibase in the coming month.

Docusaurus allows for custom "pages", which would work perfectly for this kind of table. The kicker is that it's React based, so I'll not accept this PR since it's Svelete (and not in docusaurus). However, there's enough ground work here in place that I could copy most of the HTML and business logic if that's cool with you.

**Comment by gavinr** [comment]
No problem. I'll host at https://emojibase-browser.gavinr.com/ for now - if you want to link there in the interim, feel free. Thanks!

**Comment by milesj** [comment]
@gavinr Updated the readme with a link. Thank you!

**Pull request closed without merging**
