### PR TITLE
94% translated shortcodes.po into Swedish

### PR DESCRIPTION
**Pull request by bittin**

### CODE REVIEW

**Comment by milesj** [comment]
@bittin This is absolutely amazing, thank you 🙏 

Should I wait for this to be 100% translated before merging?

**Comment by bittin** [comment]
@milesj you can wait until me or someone else finishes it up, however i have a cold and headache at the moment, so might continue with it this week, but might check some more next week

**Comment by milesj** [comment]
@bittin That's fine! The next release won't happen for a while so I'll leave this open.

**Comment by bittin** [comment]
Continued with this today during the GNOME Hackaton at foss-north Online 2021: https://foss-north.se/2021/ will post an updated file when i am done after the day ends

**Comment by bittin** [comment]
Updated in #106

**Pull request closed without merging**
